### ISSUE TITLE
hi, do you completed nest-authz with that example?

### ISSUE THREAD

**Issue by rmros** [dreamdevil00/nest-authz#1]

**Comment by dreamdevil00** [comment]
yes, what's the problem?

**Comment by rmros** [comment]
hello mr @dreamdevil00 , im thank you for nest-authz
i have some questions:
privacy.csv  :
`p, superuser, user, read:any
p, manager, user_roles, read:any
p, guest, user, read:own

g, alice, superuser
g, bob, guest
g, tom, manager

g, users_list, user
g, user_roles, user
g, user_permissions, user
g, roles_list, role
g, role_permissions, role`

i cant find any relationship between these privacy 
g, roles_list, role
g, role_permissions, role
with other top privacies rules

what's my problem?

**Comment by rmros** [comment]
next quastion:
how i can use nest-authz as multi tenant RBAC?

**Comment by rmros** [comment]
i review example completly but do you have any other real-world project its used nest-authz as authorization system to i check those code's?

**Comment by dreamdevil00** [comment]
@rmros The example only shows how to implement RBAC core with read and write scope extension. `nest-authz` does not restrict what access control model you have. 

If you want to use it in a multi tenant app, you have to define your own access control model. 
Please refer to [the casbin docs](https://casbin.org/docs/en/rbac-with-domains) for more info.

In addition, the example model mixed with `RBAC with resource roles`. Refer to [Casbin Online Editor](https://casbin.org/en/editor/) for more model example.

Hope this will help you.

**Comment by rmros** [comment]
@dreamdevil00 thank you to reply me , i got my answer completely,
do you look at nestjsx/crud  (https://github.com/nestjsx/crud) ?
its nestJs CRUD for RESTful APIs, meaning it can generate endpoints automatically for each controller,
i like to know how we can use nestjs-authz with Crud,
how we can define @usepremission decorator for each endpoint with those method(Get/Post/ ...)
